Updates for v10 release
fauna/fauna-shell pull request #224
Opened 2023-08-15 16:26 UTC by macmv

Updates things to release the shell for v10. Changes include:

- Change default eval format to use isatty in all versions
- Default to v10 for fauna shell and fauna eval
- Update description and examples of eval/shell
- Update README for v10

2023-08-15 17:22 UTC, breinero requested changes
Only a minor grammatical nit, but otherwise LGTM

2023-08-16 16:21 UTC, freels approved these changes
@breinero feels like the mini-tutorial could be moved/replaced with docs. At the very least it deserves a refresh to showcase v10 features.

2023-08-16 16:23 UTC, freels requested changes
Actually there are quite a few more FaunaDB references that need to be fixed.

2023-08-16 16:24 UTC, freels commented on README.md
>  Once you have the prompt ready, you can start issues queries against your FaunaDB instance. (Note that the results shown here might vary from the ones you see while running the examples).
```suggestion
Once you have the prompt ready, you can start issues queries against your Fauna database. (Note that the results shown here might vary from the ones you see while running the examples).
```

2023-08-16 22:49 UTC, freels approved these changes

2023-08-16 22:49 UTC, freels commented on docs/dev.md
> +Connecting to the Fauna Cloud should be as easy as typing: `$ fauna cloud-login`. The user will be prompted for their email & passwords, and their key will be saved in the `.fauna-shell` file.
minor:

```suggestion
Connecting to Fauna should be as easy as typing: `$ fauna cloud-login`. The user will be prompted for their email & passwords, and their key will be saved in the `.fauna-shell` file.
```

2023-08-16 22:54 UTC, merged